export default {
    activeTeamId: 1,
    activePlayerId: null,
    activeFormationId: 1,
    mouseOverPlayerId: null,
    playersVisible: false,
    isLoading: true,
    match: {
        time: '14:00 Sun 24 Nov 2021',
        venue: 'Stamford Bridge, London',
    },
    formations: [
        {
            id: 1,
            name: '4-3-3',
            positions: [
                {
                    x: 10,
                    y: 50,
                },
                {
                    x: 30,
                    y: 20,
                },
                {
                    x: 30,
                    y: 40,
                },
                {
                    x: 30,
                    y: 60,
                },
                {
                    x: 30,
                    y: 80,
                },
                {
                    x: 50,
                    y: 25,
                },
                {
                    x: 50,
                    y: 50,
                },
                {
                    x: 50,
                    y: 75,
                },
                {
                    x: 70,
                    y: 25,
                },
                {
                    x: 70,
                    y: 50,
                },
                {
                    x: 70,
                    y: 75,
                },
            ],
        },

        {
            id: 2,
            name: '4-4-2',
            positions: [
                {
                    x: 10,
                    y: 50,
                },
                {
                    x: 30,
                    y: 20,
                },
                {
                    x: 30,
                    y: 40,
                },
                {
                    x: 30,
                    y: 60,
                },
                {
                    x: 30,
                    y: 80,
                },
                {
                    x: 50,
                    y: 20,
                },
                {
                    x: 50,
                    y: 40,
                },
                {
                    x: 50,
                    y: 60,
                },
                {
                    x: 50,
                    y: 80,
                },
                {
                    x: 70,
                    y: 33,
                },
                {
                    x: 70,
                    y: 66,
                },
            ],
        },
        {
            id: 3,
            name: '4-2-3-1',
            positions: [
                {
                    x: 10,
                    y: 50,
                },
                {
                    x: 30,
                    y: 13,
                },
                {
                    x: 30,
                    y: 40,
                },
                {
                    x: 30,
                    y: 65,
                },
                {
                    x: 30,
                    y: 92,
                },
                {
                    x: 50,
                    y: 30,
                },
                {
                    x: 50,
                    y: 70,
                },
                {
                    x: 70,
                    y: 25,
                },
                {
                    x: 70,
                    y: 50,
                },
                {
                    x: 70,
                    y: 75,
                },
                {
                    x: 87,
                    y: 50,
                },
            ],
        },
        {
            id: 4,
            name: '4-5-1',
            positions: [
                {
                    x: 10,
                    y: 50,
                },
                {
                    x: 30,
                    y: 20,
                },
                {
                    x: 30,
                    y: 40,
                },
                {
                    x: 30,
                    y: 60,
                },
                {
                    x: 30,
                    y: 80,
                },
                {
                    x: 50,
                    y: 25,
                },
                {
                    x: 50,
                    y: 50,
                },
                {
                    x: 50,
                    y: 75,
                },
                {
                    x: 60,
                    y: 37,
                },
                {
                    x: 60,
                    y: 62,
                },
                {
                    x: 80,
                    y: 50,
                },
            ],
        },
        {
            id: 5,
            name: '3-5-2',
            positions: [
                {
                    x: 10,
                    y: 50,
                },
                {
                    x: 25,
                    y: 25,
                },
                {
                    x: 25,
                    y: 50,
                },
                {
                    x: 25,
                    y: 75,
                },
                {
                    x: 42,
                    y: 40,
                },
                {
                    x: 42,
                    y: 60,
                },
                {
                    x: 55,
                    y: 15,
                },
                {
                    x: 55,
                    y: 50,
                },
                {
                    x: 55,
                    y: 85,
                },

                {
                    x: 70,
                    y: 33,
                },
                {
                    x: 70,
                    y: 66,
                },
            ],
        },
    ],
    teams: [
        {
            id: 1,
            home: true,
            title: 'Chelsea',
            color: '#3750b1',
            formationId: 1,
            players: [
                {
                    id: 1,
                    teamId: 1,
                    firstName: 'Kepa',
                    lastName: 'Arrizabalaga',
                    position: 'Goalkeeper',
                    number: '1',
                    thumbnail: 'chelsea-th-1.png',
                    hero: 'chelsea-hero-1.jpg',
                    dob: 'October 3, 1994',
                    nationality: 'Ondarroa, ES',
                    matches: 14,
                    saves: 25,

                    cleanSheets: 3,
                    goals: 0,
                    assists: 0,
                    weight: 88,
                    height: 186,
                    bio:
                        'The Spanish international goalkeeper signed a seven-year contract at Stamford Bridge and ended his first season with silverware as we beat Arsenal in the Europa League final. He played 54 games in all competitions, including 36 in the Premier League. In total he kept an impressive 23 clean sheets as he quickly adapted to the rigours of English football. ',
                },
                {
                    id: 2,
                    teamId: 1,
                    firstName: 'Antonio',
                    lastName: 'Rudiger',
                    position: 'Defender',
                    number: '2',
                    thumbnail: 'chelsea-th-2.png',
                    hero: 'chelsea-hero-2.jpg',
                    dob: 'March 3, 1993',
                    nationality: 'Berlin, DE',
                    matches: 1,
                    saves: null,

                    cleanSheets: null,
                    goals: 0,
                    assists: 0,
                    weight: 85,
                    height: 190,
                    bio:
                        'Antonio Rudiger joined Chelsea from Italian side Roma on 9 July 2017. He signed a five-year contract. A tough tackler, Rudiger is quick on his feet and a commanding presence in the air. Despite having spent most of his career playing in central defence, he is equally comfortable at full-back. Born in Berlin, Rudiger spent time in the youth set-up at Borussia Dortmund before moving to Stuttgart. He made his Stuttgart debut in a 2012 game against Borussia Monchengladbach at the age of 18, and firmly established himself as a first-team regular during the 2013/14 campaign.',
                },
                {
                    id: 3,
                    teamId: 1,
                    firstName: 'Marcus',
                    lastName: 'Alonso',
                    position: 'Defender',
                    number: '3',
                    thumbnail: 'chelsea-th-3.png',
                    hero: 'chelsea-hero-3.jpg',
                    dob: 'December 28, 1990',
                    nationality: 'Mardin, ES',
                    matches: 7,
                    saves: null,
                    cleanSheets: null,
                    goals: 1,
                    assists: 2,
                    weight: 85,
                    height: 188,
                    bio:
                        'Alonso was born in Madrid and is the son and grandson of former Spain internationals. He was a youth and B-team player for Real Madrid, before being handed his one first team appearance there by Manuel Pellegrini in April 2010 as a late substitute in a win against Racing Santander. That summer he joined Bolton Wanderers as a 19-year-old and was a team-mate of Gary Cahill for one-and-a-half years prior to the England international’s move to Chelsea.',
                },
                {
                    id: 4,
                    teamId: 1,
                    firstName: 'Andreas',
                    lastName: 'Christensen',
                    position: 'Defender',
                    number: '4',
                    thumbnail: 'chelsea-th-4.png',
                    hero: 'chelsea-hero-4.jpg',
                    dob: 'Apri 10, 1996',
                    nationality: 'Lillerød, DK',
                    matches: 6,
                    saves: null,
                    cleanSheets: null,
                    goals: 0,
                    assists: 0,
                    weight: 82,
                    height: 187,
                    bio:
                        'A tall, ball-playing centre-back, Andreas Christensen spent eight years at Brondby before joining Chelsea ahead of many other suitors before the 2012/13 campaign. He wasted little time in displaying his composure and assuredness at the heart of defence for our youth team, impressing enough to earn himself an Under-21 debut before Christmas; however it was in the FA Youth Cup where he most grabbed attention.',
                },
                {
                    id: 5,
                    teamId: 1,
                    firstName: '',
                    lastName: 'Jorghino',
                    position: 'Midfielder',
                    number: '5',
                    thumbnail: 'chelsea-th-5.png',
                    hero: 'chelsea-hero-5.jpg',
                    dob: 'December 20, 1991',
                    nationality: 'Imbituba, BR',
                    matches: 13,
                    saves: null,
                    cleanSheets: null,
                    goals: 1,
                    assists: 2,
                    weight: 68,
                    height: 180,
                    bio:
                        'The Italian international is a highly technical midfielder capable of dictating the tempo of play in possession with quick passing and movement. He has most often been deployed as a deep-lying playmaker in a midfield three, using his ability to link defence and attack. ',
                },
                {
                    id: 6,
                    teamId: 1,
                    firstName: "N'Golo",
                    lastName: 'Kante',
                    position: 'Midfielder',
                    number: '7',
                    thumbnail: 'chelsea-th-7.png',
                    hero: 'chelsea-hero-7.jpg',
                    dob: 'March 29, 1991',
                    nationality: 'Paris, FR',
                    matches: 7,
                    saves: null,
                    cleanSheets: null,
                    goals: 3,
                    assists: 0,
                    weight: 70,
                    height: 168,
                    bio:
                        "N'Golo Kante was a major addition to the squad for the 2016/17 season, signing a five-year contract for Chelsea. Kante joined from Leicester City, where he so memorably played a major part in the Foxes’ Premier League triumph the previous season. The then 25-year-old came close to adding to that success on the international stage soon after. He was part of the France squad that was denied a host-team triumph at Euro 2016 by an extra-time Portugal goal in the final.",
                },
                {
                    id: 7,
                    teamId: 1,
                    firstName: 'Ross',
                    lastName: 'Barkley',
                    position: 'Midfielder',
                    number: '8',
                    thumbnail: 'chelsea-th-8.png',
                    hero: 'chelsea-hero-8.jpg',
                    dob: 'December 5, 1993',
                    nationality: 'Liverpool, EN',
                    matches: 6,
                    saves: null,

                    cleanSheets: null,
                    goals: 0,
                    assists: 0,
                    weight: 87,
                    height: 186,
                    bio:
                        'Ross Barkley became a Chelsea player when he moved to Stamford Bridge from Everton in January 2018. He signed a five-and-a-half-year contract and was given the number 8 shirt.',
                },
                {
                    id: 8,
                    teamId: 1,
                    firstName: '',
                    lastName: 'Pedro',
                    position: 'Forward',
                    number: '11',
                    thumbnail: 'chelsea-th-11.png',
                    hero: 'chelsea-hero-11.jpg',
                    dob: 'July 28, 1987 ',
                    nationality: 'Santa Cruz de Tenerife, ES',
                    matches: 4,
                    saves: null,

                    cleanSheets: null,
                    goals: 0,
                    assists: 0,
                    weight: 67,
                    height: 169,
                    bio:
                        'A talented two-footed winger, who is also capable of playing more centrally, Pedro arrived at Stamford Bridge with a fantastic pedigree having already enjoyed success at the highest level at club and international level, which he added to as a Blues player.',
                },
                {
                    id: 9,
                    teamId: 1,
                    firstName: '',
                    lastName: 'Willian',
                    position: 'Midfield',
                    number: '10',
                    thumbnail: 'chelsea-th-10.png',
                    hero: 'chelsea-hero-10.jpg',
                    dob: 'August 9, 1988',
                    nationality: 'Ribeirao Pires, BR',
                    matches: 13,
                    saves: null,

                    cleanSheets: null,
                    goals: 2,
                    assists: 3,
                    weight: 77,
                    height: 175,
                    bio:
                        'The purchase of Willian was completed in late August 2013, the Brazilian signing a five-year contract on moving to England from Russian club Anzhi Makhachka. Chelsea fans knew what they were getting when the Blues brought Willian to the club, having seen him net twice in a virtuoso display for Shakhtar Donetsk at the Bridge in 2012.',
                },
                {
                    id: 10,
                    teamId: 1,
                    firstName: 'Oliver',
                    lastName: 'Giroud',
                    position: 'Forward',
                    number: '18',
                    thumbnail: 'chelsea-th-18.png',
                    hero: 'chelsea-hero-18.jpg',
                    dob: 'September 30, 1986',
                    nationality: 'Chambéry, France',
                    matches: 5,
                    saves: null,

                    cleanSheets: null,
                    goals: 0,
                    assists: 0,
                    weight: 91,
                    height: 193,
                    bio:
                        'Olivier Giroud moved across London to Chelsea from Arsenal in January 2018 and signed an 18-month contract at Stamford Bridge. The striker arrived with a proven pedigree at the highest level having scored goals regularly in the Premier League, in Europe and on the international stage for France.',
                },
                {
                    id: 11,
                    teamId: 1,
                    firstName: 'Mason',
                    lastName: 'Mount',
                    position: 'Midfield',
                    number: '19',
                    thumbnail: 'chelsea-th-19.png',
                    hero: 'chelsea-hero-19.jpg',
                    dob: 'January 10, 1999',
                    nationality: 'Portsmouth, GB',
                    matches: 14,
                    saves: null,

                    cleanSheets: null,
                    goals: 4,
                    assists: 1,
                    weight: 70,
                    height: 178,
                    bio:
                        'Mason Mount has been training at the club since he was six years old and signed at the Under-9 age group. He has always been an attacking midfielder, capable of playing in any of the central midfield roles and is particularly strong at going from box-to-box.',
                },
            ],
        },
        {
            id: 2,
            home: false,
            title: 'Barcelona',
            color: '#c9181d',
            formationId: 1,
            players: [
                {
                    id: 31,
                    teamId: 2,
                    x: 87,
                    y: 50,
                    firstName: 'Marc-André',
                    lastName: 'ter Stegen',
                    position: 'Goalkeeper',
                    number: '1',
                    thumbnail: 'barcelona-th-1.png',
                    hero: 'chelsea-hero-1.jpg',
                    dob: 'April 30, 1992',
                    nationality: 'Mönchengladbach, DE',
                    matches: 209,
                    saves: 535,

                    cleanSheets: 86,
                    goals: 0,
                    assists: 0,
                    weight: 85,
                    height: 187,
                    bio:
                        'Ter Stegen has been playing at the top level of the game since the age of 19. Excellent with the ball at his feet, he is a player for the present and the future.',
                },
                {
                    id: 30,
                    teamId: 2,
                    x: 70,
                    y: 75,
                    firstName: 'Nélson',
                    lastName: 'Semedo',
                    position: 'Defender',
                    number: '2',
                    thumbnail: 'barcelona-th-2.png',
                    hero: 'chelsea-hero-1.jpg',
                    dob: 'November 16, 1993',
                    nationality: 'Lisboa, PT',
                    matches: 96,
                    saves: null,

                    cleanSheets: null,
                    goals: 1,
                    assists: 4,
                    weight: 67,
                    height: 177,
                    bio:
                        'Nélson Cabral Semedo, born 16 November 1993, joined Benfica in 2012 from Sintrense. He went back on loan to his former club for a year before becoming a full time member of the Eagles’ reserves. He performed brilliantly for the second team, and made his first team debut in the 2015 Portuguese Super Cup against Sporting Lisbon.',
                },
                {
                    id: 29,
                    teamId: 2,
                    x: 70,
                    y: 50,
                    firstName: 'Gerard',
                    lastName: 'Piqué',
                    position: 'Defender',
                    number: '3',
                    thumbnail: 'barcelona-th-3.png',
                    hero: 'chelsea-hero-1.jpg',
                    dob: 'February 2, 1987',
                    nationality: 'Barcelona, ES',
                    matches: 2,
                    saves: null,

                    cleanSheets: null,
                    goals: 0,
                    assists: 0,
                    weight: 85,
                    height: 194,
                    bio:
                        'Considered one of the best centre halves in the world, Gerard Piqué brings together character, class and strength in the air at centre back, something that has made him a key figure in the Barça team.',
                },
                {
                    id: 28,
                    teamId: 2,
                    x: 70,
                    y: 25,
                    firstName: 'Sergio',
                    lastName: 'Busquets',
                    position: 'Midfield',
                    number: '5',
                    thumbnail: 'barcelona-th-5.png',
                    hero: 'chelsea-hero-1.jpg',
                    dob: 'July 16, 1988',
                    nationality: 'Sabadell, ES',
                    matches: 551,
                    saves: null,

                    cleanSheets: null,
                    goals: 14,
                    assists: 30,
                    weight: 76,
                    height: 189,
                    bio:
                        'Sergio Busquets is probably the best defensive midfielder in the world. He stands out for his technical ability and his unsurpassed reading of the game.',
                },
                {
                    id: 27,
                    teamId: 2,
                    x: 70,
                    y: 25,
                    firstName: 'Jean-Clair ',
                    lastName: 'Todibo',
                    position: 'Midfield',
                    number: '6',
                    thumbnail: 'barcelona-th-6.png',
                    hero: 'chelsea-hero-1.jpg',
                    dob: 'December 30, 1999',
                    nationality: ' French Guianese, FR',
                    matches: 2,
                    saves: null,
                    cleanSheets: null,
                    goals: 0,
                    assists: 0,
                    weight: 81,
                    height: 190,
                    bio: 'Bio',
                },
                {
                    id: 26,
                    teamId: 2,
                    x: 52,
                    y: 92,
                    firstName: 'Carkes',
                    lastName: 'Aleñá',
                    position: 'Midfielder',
                    number: '19',
                    thumbnail: 'barcelona-th-19.png',
                    hero: 'chelsea-hero-1.jpg',
                    dob: 'January 5, 1998',
                    nationality: 'Mataró, ES',
                    matches: 34,
                    saves: null,

                    cleanSheets: null,
                    goals: 3,
                    assists: 0,
                    weight: 73,
                    height: 180,
                    bio:
                        'Carles Aleñá has been an FC Barcelona player since the age of eight. His natural ability has seen him rise quickly through the youth teams to reach Barça B. When he was a still officially an U19A player, he was already a fixture in the B squad.',
                },
                {
                    id: 25,
                    teamId: 2,
                    x: 48,
                    y: 65,
                    firstName: '',
                    lastName: 'Arthur',
                    position: 'Midfielder',
                    number: '8',
                    thumbnail: 'barcelona-th-8.png',
                    hero: 'chelsea-hero-1.jpg',
                    dob: 'August 12, 1996',
                    nationality: 'Goiânia, BR',
                    matches: 55,
                    saves: null,
                    cleanSheets: null,
                    goals: 2,
                    assists: 6,
                    weight: 73,
                    height: 171,
                    bio:
                        'Midfielder with great ball control, he stands out for his vertical play, good field vision, and great passing ability. Born on August 12, 1996 in the Brazilian town of Goiania, Arthur Melo is a young midfielder who stands out for his ability to organize play and his teamwork, as well as for his vertical play and passing skills.',
                },

                {
                    id: 24,
                    teamId: 2,
                    x: 52,
                    y: 13,
                    firstName: 'Ican',
                    lastName: 'Rakitic',
                    position: 'Midfield',
                    number: '4',
                    thumbnail: 'barcelona-th-4.png',
                    hero: 'chelsea-hero-1.jpg',
                    dob: 'March 10, 1988',
                    nationality: 'Rheinfelden, CH',
                    matches: 279,
                    saves: null,
                    cleanSheets: null,
                    goals: 35,
                    assists: 36,
                    weight: 78,
                    height: 184,
                    bio:
                        'A key member of the Croatia national side and FC Barcelona, Ivan Rakitic is a midfielder who brings hard work, assists and goals, such as the one he scored in the 2015 Champions League final in Berlin.',
                },
                {
                    id: 23,
                    teamId: 2,
                    x: 30,
                    y: 70,
                    firstName: 'Ousmane',
                    lastName: 'Dembélé',
                    position: 'Forward',
                    number: '11',
                    thumbnail: 'barcelona-th-11.png',
                    hero: 'chelsea-hero-3.jpg',
                    dob: 'May 15, 1997',
                    nationality: 'Vernon, FR',
                    matches: 74,
                    saves: null,
                    cleanSheets: null,
                    goals: 19,
                    assists: 15,
                    weight: 75,
                    height: 180,
                    bio:
                        'The French winger is one of most exciting dribblers in football and thrives on troubling rival defences both for club and country.',
                },
                {
                    id: 22,
                    teamId: 2,
                    x: 30,
                    y: 30,
                    firstName: 'Luis',
                    lastName: 'Suárez',
                    position: 'Attacker',
                    number: '9',
                    thumbnail: 'barcelona-th-9.png',
                    hero: 'chelsea-hero-2.jpg',
                    dob: 'January 24, 1987',
                    nationality: 'Salto, UY',
                    matches: 263,
                    saves: null,

                    cleanSheets: null,
                    goals: 187,
                    assists: 88,
                    weight: 86,
                    height: 182,
                    bio:
                        'Luis Suárez is synonymous with goals, scoring them and creating them. The Barça number 9 has a fighting quality that makes him a winner through and through',
                },
                {
                    id: 21,
                    teamId: 2,
                    x: 13,
                    y: 50,
                    firstName: '',
                    lastName: 'Messi',
                    position: 'Forward',
                    number: '10',
                    thumbnail: 'barcelona-th-10.png',
                    hero: 'chelsea-hero-1.jpg',
                    dob: 'June 24, 1987',
                    nationality: 'Rosario, AR',
                    matches: 701,
                    saves: null,

                    cleanSheets: null,
                    goals: 614,
                    assists: 259,
                    weight: 72,
                    height: 170,
                    bio:
                        'Leo Messi is the best player in the world. Technically perfect, he brings together unselfishness, pace, composure and goals to make him number one.',
                },
            ],
        },
    ],
};
